name: app_egressos
description: "Aplicativo Mobile para Gestão e Engajamento de Egressos da UNIT"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ========== STATE MANAGEMENT ==========
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  bloc_concurrency: ^0.3.0

  # ========== DEPENDENCY INJECTION ==========
  get_it: ^8.2.0
  injectable: ^2.4.2

  # ========== NAVIGATION ==========
  go_router: ^16.2.4

  # ========== NETWORK ==========
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.4.1

  # ========== FIREBASE ==========
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_remote_config: ^5.0.4
  firebase_performance: ^0.10.0+4
  firebase_dynamic_links: ^6.0.4

  # ========== AUTHENTICATION ==========
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  local_auth: ^2.2.0

  # ========== LOCAL STORAGE ==========
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.0.5

  # ========== IMAGES & MEDIA ==========
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  photo_view: ^0.15.0
  flutter_native_image: ^0.0.6+1
  image: ^4.2.0

  # ========== UI COMPONENTS ==========
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^4.0.3
  badges: ^3.1.2
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  expandable: ^5.0.1
  readmore: ^3.0.0

  # ========== FORMS & VALIDATION ==========
  validators: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  brasil_fields: ^1.15.0
  cpf_cnpj_validator: ^2.0.0
  email_validator: ^3.0.0

  # ========== DATE & TIME ==========
  intl: any  # Gerenciado pelo flutter_localizations
  timeago: ^3.7.0
  table_calendar: ^3.1.2

  # ========== UTILS ==========
  uuid: ^4.4.2
  url_launcher: ^6.3.0
  share_plus: ^12.0.0
  device_info_plus: ^12.1.0
  package_info_plus: ^8.0.0
  app_settings: ^6.1.1
  vibration: ^3.1.4
  flutter_native_splash: ^2.4.1

  # ========== PERMISSIONS ==========
  permission_handler: ^12.0.1

  # ========== NOTIFICATIONS ==========
  flutter_local_notifications: ^19.4.2
  awesome_notifications: ^0.10.1

  # ========== QR CODE ==========
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^7.1.2

  # ========== MAPS & LOCATION ==========
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^3.1.0

  # ========== CHARTS & GRAPHS ==========
  fl_chart: ^1.1.0
  syncfusion_flutter_charts: ^31.1.19

  # ========== PDF ==========
  pdf: ^3.11.0
  printing: ^5.13.1
  flutter_pdfview: ^1.3.2

  # ========== VIDEO ==========
  video_player: ^2.9.1
  youtube_player_flutter: ^9.0.3

  # ========== WEBVIEW ==========
  webview_flutter: ^4.8.0

  # ========== ANALYTICS & MONITORING ==========
  sentry_flutter: ^9.6.0

  # ========== FUNCTIONAL PROGRAMMING ==========
  dartz: ^0.10.1
  rxdart: ^0.28.0

  # ========== HTTP CLIENT ALTERNATIVES ==========
  http: ^1.2.2

  # ========== JSON ==========
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4  # Movido para dependencies

  # ========== CUPERTINO (iOS) ==========
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ========== LINTING ==========
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

  # ========== CODE GENERATION ==========
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  freezed: ^2.5.2

  # ========== TESTING ==========
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  faker: ^2.1.0
  network_image_mock: ^2.1.1
  integration_test:
    sdk: flutter

  # ========== ICONS ==========
  flutter_launcher_icons: ^0.14.4

# ========== FLUTTER LAUNCHER ICONS ==========
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
  # iOS specific
  remove_alpha_ios: true
  
  # Android specific
  min_sdk_android: 21

# ========== FLUTTER NATIVE SPLASH ==========
flutter_native_splash:
  color: "#1976D2"
  image: assets/images/splash_logo.png
  branding: assets/images/unit_logo.png
  color_dark: "#0D47A1"
  image_dark: assets/images/splash_logo_dark.png
  
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#1976D2"
    
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  
  # ========== ASSETS ==========
  assets:
    # Images
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/placeholders/
    - assets/images/backgrounds/
    - assets/images/illustrations/
    
    # Icons
    - assets/icons/
    - assets/icons/social/
    - assets/icons/categories/
    
    # Animations
    - assets/animations/
    - assets/animations/lottie/
    - assets/animations/loading/
    - assets/animations/success/
    - assets/animations/error/
    - assets/animations/empty/
    
    # Fonts (se necessário)
    # - assets/fonts/
    
    # Documents
    - assets/docs/
    - assets/docs/terms_of_service.pdf
    - assets/docs/privacy_policy.pdf

  # ========== FONTS ==========
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
  #   
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600