name: backend
description: Backend em Dart com Shelf + PostgreSQL
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.3
  dotenv: ^4.2.0
  logging: ^1.2.0
  dart_jsonwebtoken: ^2.12.0
  crypto: ^3.0.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  mocktail: ^1.0.0
  http: ^1.1.0