// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWo2nMMWpTbeH0xTiars_GmKfiY4dFPsQ',
    appId: '1:356248282561:web:97bed0cd3702bbcbc9fb40',
    messagingSenderId: '356248282561',
    projectId: 'egressos-unit',
    authDomain: 'egressos-unit.firebaseapp.com',
    storageBucket: 'egressos-unit.firebasestorage.app',
    measurementId: 'G-44HLVP6VLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCaNheSnXethwAwNL3HTbPQI1FgZgMK0',
    appId: '1:356248282561:android:043ad10119d2be10c9fb40',
    messagingSenderId: '356248282561',
    projectId: 'egressos-unit',
    storageBucket: 'egressos-unit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfpM2pOcPqxdJvP_qRvh2W91jwe9ZahA',
    appId: '1:356248282561:ios:db0cd37978f131e3c9fb40',
    messagingSenderId: '356248282561',
    projectId: 'egressos-unit',
    storageBucket: 'egressos-unit.firebasestorage.app',
    iosBundleId: 'br.edu.unit.appEgressos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfpM2pOcPqxdJvP_qRvh2W91jwe9ZahA',
    appId: '1:356248282561:ios:db0cd37978f131e3c9fb40',
    messagingSenderId: '356248282561',
    projectId: 'egressos-unit',
    storageBucket: 'egressos-unit.firebasestorage.app',
    iosBundleId: 'br.edu.unit.appEgressos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWo2nMMWpTbeH0xTiars_GmKfiY4dFPsQ',
    appId: '1:356248282561:web:3b37b6fdb771bee0c9fb40',
    messagingSenderId: '356248282561',
    projectId: 'egressos-unit',
    authDomain: 'egressos-unit.firebaseapp.com',
    storageBucket: 'egressos-unit.firebasestorage.app',
    measurementId: 'G-S0NQZRCT0N',
  );
}
